---
name: Update Bazel

on:
  pull_request:
    branches:
    - dependabot/go_modules/**
  push:
    branches:
    - dependabot/go_modules/**

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

jobs:
  update-bazel:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make gomod
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make gomod

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update Bazel files
          branch: ${{ github.head_ref }}
          repository: ${{ env.GOPATH }}/src/k8s.io/kops
